### ISSUE TITLE
use question

### ISSUE THREAD

**Issue by StevesHarrington** [En73r/DBDEazyQTE#5]
1. Which of the three levels of electrotherapy should be used to get rid of control when facing the doctor？
2. Merciless Storm，Which key should be used？Need to close Hyperfocus？

**Comment by En73r** [comment]
1. The electrotherapy problem is not fully solved yet, if the QTE appears in the center of the screen, repairing mode would be ok with it, otherwise, this program won't work.
2. No key is needed. it's totally automatic.
