### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by kkwoff** [En73r/DBDEazyQTE#6]
Hello, I see the source code contains 2560x1600, then I am 2560x1440 can I use

**Comment by En73r** [comment]
2560x1440 is the default.

**Comment by kkwoff** [comment]
oh！Sorry！ I didn't find it

**Comment by En73r** [comment]
it's ok

**Comment by En73r** [comment]
It's ok. It's not explicitly written in the code. Not ur problem.
