### ISSUE TITLE
Insconsistency

### ISSUE THREAD

**Issue by MrOzymandyas** [En73r/DBDEazyQTE#7]
The QTEs seem to be hit or miss for me, no matter the type 40% of them fail... Even with delay adjustments. Sometimes the executable crashes.
Is there any extra configuration I should make to play at full HD?

**Comment by En73r** [comment]
Try to use HDR if available. This program is based on image recognition, therefore the color of the pixel is vital to it. I suppose that a lot of players like to change their graphic filter to make it more bright to see every detail in the game, but that will significantly impact the consistency of the program. You may post one of your screenshots with QTE circle or crops in the `DBDimg` directory, and I can check it for you. PS with one of mine, you can check out if there are some differences with yours 
![log_-8 231913004431235_speed_330](https://user-images.githubusercontent.com/82085737/202887640-00a35b80-a0d0-4314-bf93-f42b8691295a.png)

**Comment by MrOzymandyas** [comment]
I've managed to increase accuracy to almost perfection trough darkening of the screen using my graphics card settings, though the wiggle mechanism seems to only miss no matter what I do.

**Comment by En73r** [comment]
This program only features the new wiggle. It means you need to toggle on the new wiggle in the beta column of settings. Hope this will help you
